### ISSUE TITLE
submodule automagisch updaten

### ISSUE THREAD

**Issue by sedrubal** [fau-fablab/buildserver#1]
Spricht was dagegen, dass der buildserver automagisch die submodule aktualisiert und falls sie sich aktualisiert haben, das dann wieder auf github zu pushen?

**Comment by mgmax** [comment]
Ich zweifle mal stark an, dass automatische commits eine gute Idee sind. 
TODO hier böses Szenario einfügen :)

Allerdings wäre es kein Problem, "submodule tracking branches" zu 
verwenden (`git submodule add ... -b master`) und den buildserver `git 
submodule update --remote` machen zu lassen.
Das kann man auch in der .gitmodules nachtragen, siehe die Zeile 
"branch" bei 
https://github.com/fau-fablab/document-dummy/blob/master/.gitmodules
So hat man die Möglichkeit, bei breaking changes in der Vorlage auch mal 
explizit den tracking-branch zu entfernen und eine alte Version der 
Vorlage weiterzunutzen.

**Comment by sedrubal** [comment]
Umbauen auf submodule die anhand von Branches ausgecheckt werden.

**Comment by Balagrio** [comment]
was ist denn mit dir?

**Comment by sedrubal** [comment]
ich hab festgestellt, dass man mit ![clustergit](https://github.com/mnagel/clustergit) auch sehr weit kommt und dann denke ich, kann man den issue schließen...

**Comment by mgmax** [comment]
Ja. Und wie man oft genug gesehen hat, macht ein automagisches update viel zu oft was kaputt (z.B. bei der globalen Einbindung von todonotes).
