### ISSUE TITLE
regelmäßig output Verzeichnis löschen

### ISSUE THREAD

**Issue by mgmax** [fau-fablab/buildserver#3]
in https://user.fablab.fau.de/~buildserver/pricelist/output/ liegen teils alte Dokumente, die man wegputzen sollte. Ursache dafür ist, dass das output-Verzeichnis einfach nur die erzeugten Dinge ansammelt, und nicht das alte Zeugs geleert wird.
Wie will man das machen? make clean + darin output/ leeren?

**Comment by sedrubal** [comment]
Ah OK.

Vielleicht will man einen 2. cronjob laufen lassen, der um 5:00 in der früh `build.sh 0 --rebuild` aufruft. Und dann gibts ein `make clean` und ein `rm -rf public-html && mkdir public-html && cp staus-icons/build-unknown.svg public-html/` und anschließend ein normales `build.sh` oder so?

**Comment by mgmax** [comment]
hmm, eigentlich gehört das Aufräumen des output/ Ordners aber mit in 
make clean rein...

**Comment by sedrubal** [comment]
Und wer räumt dann public-html auf?

**Comment by mgmax** [comment]
hm, da könnte man statt `cp -r output/ public_html/repo/` einfach `rsync 
--recursive --delete quelle/ ziel/` einsetzen.
Dann zerlegt es (solange gerade nix geändert wurde) auch nicht mehr die 
PDF-Datei wenn man genau zur Ausführungszeit gerade runterlädt.

**Comment by sedrubal** [comment]
das klingt gut, aber alte projekte sollten trdm automagisch gelöscht werden.

**Comment by mgmax** [comment]
das kann man ja noch ergänzen. Am besten wäre es, alles im Buildserver drin zu haben, z.B. als Option --clean-and-rebuild

**Comment by sedrubal** [comment]
OK, also wenn du das makefile entsprechend anpassst, kann ich den Buildserver umbauen, außer du machst schnell beides...

**Comment by mgmax** [comment]
Die Lasereinweisung und das Makefile sind jetzt angepasst, jetzt darf man nur noch mal einen Rutsch alles auf die neue Version von fablab-document updaten. Dass ein automagisches Update doof ist, hat die Lasereinweisung gerade gezeigt, die brauchte eine kleine Änderung um mit der neuen Version der Vorlage zu leben.

oerp-pricelist ist vergleichbar dazu angepasst.

Der Buildserver macht jetzt einfach immer make clean, du kannst das gerne durch eine elegantere Lösung ersetzen.

Achja viel Spaß damit, dass /home/buildserver/public_html/pricelist/ dem buildserver-oerp gehört... da kann man also nicht einfach das Verzeichnis löschen.
Workaround: Nach Verzeichnissen suchen, die schon seit X Tagen nicht geändert wurden, und diese bemeckern?

**Comment by sedrubal** [comment]
> auf die neue Version von fablab-document updaten

done

> `# TODO only run 'make clean' from time to time`

done: man kann jetzt `./build.sh all-repos clean` laufen lassen, damit make clean ausgeführt wird. Außerdem bau ich noch, dass bei dem Argument `clean` auch alte Projekte im Ouptut Ordner gelöscht werden...

**Comment by sedrubal** [comment]
Ach, @mgmax , kannst du noch im buildserver-oerp Skript einrichten, dass nach jedem Bauen der jeweilige Ordner ge`touch`t wird? Sonst kommt der buildserver durcheinander...

**Comment by mgmax** [comment]
sollte wieder alles laufen. Habe das eigentliche Verzeichnis-Löschen mal aus dem Skript rausgenommen, die Warnmeldung reicht ja.
